=== NFER179/ENABOPERATION/Solution-workspace/ab-solution/webapp/WEB-INF/conf/solution.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<!-- definition of simple elements -->
	<xsd:element name="name" type="xsd:string" />
	<xsd:element name="engine" type="xsd:string" />
	<xsd:element name="url" type="xsd:string" />
	<xsd:element name="databasename" type="xsd:string" />
	<xsd:element name="user" type="xsd:string" />
	<xsd:element name="password" type="xsd:string" />
	
	<!-- definition of composed elements  -->
	<xsd:simpleType name="typeOfLog" >
		<xsd:restriction base="xsd:string" >
			<xsd:enumeration value="info" />
			<xsd:enumeration value="debug" />
			<xsd:enumeration value="all" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<!-- definition of attribute -->
	<xsd:attribute name="active" type="xsd:boolean" />
	<!-- <xsd:attribute name="typeOfLog" type="xsd:string" /> -->
	
	<!-- definition of complex -->
	<xsd:complexType name="logComplexType">
		<xsd:sequence>
			<xsd:element ref="url" />
		</xsd:sequence>
		<xsd:attribute name="logType" type="typeOfLog" use="required" />
	</xsd:complexType>
	
	<xsd:complexType name="databasecomplextype">
		<xsd:sequence>
			<xsd:element ref="name" />
			<xsd:element ref="engine" />
			<xsd:element ref="url" />
			<xsd:element ref="databasename" />
			<xsd:element ref="user" />
			<xsd:element ref="password" />
		</xsd:sequence>
		<xsd:attribute ref="active" use="required" />
	</xsd:complexType>

	<xsd:complexType name="databasescomplextype">
		<xsd:sequence>
			<xsd:element name="database" maxOccurs="unbounded" minOccurs="1" type="databasecomplextype" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="solution">
		<xsd:sequence>
			<xsd:element name="log" type="logComplexType"/>
			<xsd:element name="databases" type="databasescomplextype"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:element name="solution-properties" type="solution" />

</xsd:schema>

=== NFER179/ENABOPERATION/Solution-workspace/ab-solution/webapp/WEB-INF/conf/solution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE XML> -->
<solution-properties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="solution.xsd">
	<log logType="info">
		<url>C:\Users\nfernandez\Desktop\Toc\02-Proyectos\01-Customs\01-Contratos\</url>
	</log>
	<databases>
		<database active="true">
			<name>AbSolution sqlite</name>
			<engine>sqlite</engine>
			<url>C:\Users\nfernandez\Desktop\Toc\02-Proyectos\01-Customs\01-Contratos\02-DataBase\databases</url>
			<databasename>AbSolution.db</databasename>
			<user></user>
			<password></password>
		</database>
	</databases>
</solution-properties>

=== NFER179/ENABOPERATION/Solution-workspace/ab-solution/webapp/WEB-INF/conf/example-solution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE XML> -->
<solution-properties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="solution.xsd">
	<log logType="info">
		<url>Path</url>
	</log>
	<structure>
		<pathOfStructure>StructPath</pathOfStructure>
	</structure>
	<databases>
		<database active="true">
			<name>AbSolution sqlite</name>
			<engine>sqlite</engine>
			<url>path</url>
			<databasename>database.sdb</databasename>
			<user></user>
			<password></password>
		</database>
		<database active="false">
			<name>AbSolution sql server</name>
			<engine>sqlServer</engine>
			<url></url>
			<databasename></databasename>
			<user></user>
			<password></password>
		</database>
	</databases>
</solution-properties>
